### ISSUE TITLE
Invalid key SHARDING

### ISSUE THREAD

**Issue by download13** [ipfs/js-datastore-core#2]
I get the following error when running `npm test` on Windows 10.

This also results in a failed build when using `js-ipfs` which depends on it.

```
Error: Invalid key: \SHARDING
    at new Key (C:\Users\download\Desktop\js-datastore-core\node_modules\interface-datastore\src\key.js:42:13)
    at Object.<anonymous> (C:\Users\download\Desktop\js-datastore-core\src\sharding.js:12:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\download\Desktop\js-datastore-core\src\index.js:5:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\download\Desktop\js-datastore-core\test\keytransform.spec.js:16:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\download\Desktop\js-datastore-core\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\download\Desktop\js-datastore-core\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (C:\Users\download\Desktop\js-datastore-core\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (C:\Users\download\Desktop\js-datastore-core\node_modules\mocha\bin\_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Is there a reason that the sharding keys don't conform to the rules of the `Key` class?

**Comment by dignifiedquire** [comment]
It seems the different path separators on windows are playing a trick on us here, when using `path.normalize` to generate the key. Thank you for the report

**Comment by dignifiedquire** [comment]
I don't have a windows machine to test right now, could you test with this PR https://github.com/ipfs/interface-datastore/pull/5 please, I believe it should make the tests pass on windows

**Comment by download13** [comment]
I have an alternative pull request: ipfs/interface-datastore#6

This one keeps the path style consistent and changes as little as possible.

If you're willing to add another dependency though, we could use [normalize-path](https://github.com/jonschlinkert/normalize-path) instead of my homebrew function which should always produce consistent results.

**Comment by nightwolfz** [comment]
Any progress on this? This is literally the only issue stopping me from using IPFS

**Comment by dignifiedquire** [comment]
@download13 @nightwolfz I just merged the PR, I was able to get it working including passing CI on appveyor so it doesn't break immediately again. 

We will release bubble up the changes in the coming days, so a fix should be soon available in js-ipfs itself

**Comment by diasdavid** [comment]
👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽 :D thank you, @dignifiedquire

**Comment by diasdavid** [comment]
The problem persists. @dignifiedquire did you remember testing it?

**Comment by dignifiedquire** [comment]
I never tested the upper layers I think.

**Comment by richardschneider** [comment]
PR https://github.com/ipfs/interface-datastore/pull/12 fixes the windows issue.

Perhaps someone could review it.

**Comment by diasdavid** [comment]
Being fixed with https://github.com/ipfs/js-datastore-core/pull/3
